artifact_location: file:///E:/Computer_Vision/vision-based-uav-detection/runs/mlflow/902508114332216184
creation_time: 1767350344666
experiment_id: '902508114332216184'
last_update_time: 1767350344666
lifecycle_stage: active
name: e:\Computer_Vision\vision-based-uav-detection\runs
