artifact_location: file:///E:/Computer_Vision/vision-based-uav-detection/runs/mlflow/0
creation_time: 1767350344601
experiment_id: '0'
last_update_time: 1767350344601
lifecycle_stage: active
name: Default
